src/src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Annonce $id_annonce = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $id_user = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $creation_date = null;

    #[ORM\Column(length: 255)]
    private ?string $question = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $response = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $response_date = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdAnnonce(): ?Annonce
    {
        return $this->id_annonce;
    }

    public function setIdAnnonce(?Annonce $id_annonce): self
    {
        $this->id_annonce = $id_annonce;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeImmutable
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeImmutable $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getQuestion(): ?string
    {
        return $this->question;
    }

    public function setQuestion(string $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function getResponse(): ?string
    {
        return $this->response;
    }

    public function setResponse(?string $response): self
    {
        $this->response = $response;

        return $this;
    }

    public function getResponseDate(): ?\DateTimeImmutable
    {
        return $this->response_date;
    }

    public function setResponseDate(?\DateTimeImmutable $response_date): self
    {
        $this->response_date = $response_date;

        return $this;
    }

}

src/src/Controller/ProfileController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\UserRepository;

class ProfileController extends AbstractController
{
    #[Route('/profile/{pseudo}', name: 'app_profile')]
    public function index($pseudo, UserRepository $userRepo): Response
    {
        $user_email = $this->getUser()->getUserIdentifier();
        $user = $userRepo->findBy(["email" => $user_email]);
        $user_id = $user[0]->getId();

        return $this->render('profile/index.html.twig', [
            'profile' => $userRepo->findOneBy(['pseudo'=>$pseudo]),
            'user_id' => $user_id
        ]);
    }
}

src/templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}

{% if "ROLE_ADMIN" in profile.roles %}
{% set color = "primary" %}
{% else %}
{% set color = "secondary" %}
{% endif %}


<h1><a class='{{"text-" ~ color}}'> {{profile.pseudo}}</a> profile<h1>
<div class="container">
  <div class="row">
    <!-- différent bordure dépendant rôle user/admin -->
    <div class='col-4 border border-3 border-{{ color }}'>
    <!-- -->
      <img src="/uploads/user/{{ profile.profilePicture }}" alt={{profile.profilePicture}} width="300" height="300">
    </div>
    <div class="col-8">
      <div class="row">
        {{ profile.lastname ~ " " ~ profile.firstname}}
      </div>
      <div class="row">
        cake day : {{ profile.accountCreationDate|date('Y-m-d') }}
      </div>
      {% if profile.localisation == null %}
      {% set localisation = "unknown" %}
      {% else %}
      {% set localisation = profile.localisation %}
      {% endif %}
      <div class="row">
        localisation : {{ localisation }}
      </div>
      {% if profile.id == user_id %}
        <a href="{{ path('app_user_edit') }}">Modifier mon profil</a>
      {% endif %}
      {% if profile.note == null %}
      {% set note = 0 %}
      {% else %}
      {% set note = profile.note %}
      {% endif %}
      <div class="row">
        note : {{ note }}
      </div>
    </div>
  </div>
  <!-- si admin montre les commentaires de la personnes -->
  {% if "ROLE_ADMIN" in app.user.roles %}
  <div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Vos commentaires
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <!-- controller show comment personne -->
          {% for  comment in profile.comments %}
            <li>
              <a href="{{ path('app_annonce_by_id',{id: comment.idAnnonce.id }) }}">{{profile.pseudo}}</a>

              {{comment.question}}
              {{comment.creationDate|date('Y-m-d')}}
               {{comment.id}}
              <!-- sup comment -->
              <form action="{{ path('app_comment_delete',{pseudo: profile.pseudo ,id: comment.id }) }}" method="post">
                <button class="btn btn-lg btn-primary m-auto mb-4" type="submit">
                  delete
                </button>
              </form>


            </li>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endif %}

</div>
{% endblock %}